# Generated by Django 5.0.6 on 2024-07-04 15:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author_app', '0001_initial'),
        ('cetagory_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='add_post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('content', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='author_app.add_author')),
                ('cetagory', models.ManyToManyField(to='cetagory_app.add_cetagory')),
            ],
        ),
    ]
